name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup dependency cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Ensure dependencies are downloaded
      run: go mod download

    - name: Build
      run: go build -v ./...

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Setup Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup dependency cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Ensure dependencies are downloaded
      run: go mod download

    - name: Test
      run: go test ./...


  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build
    steps:

    - name: Setup Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Setup golangci-lint
      env:
        GOLANGCI_LINT_VERSION: 1.24.0
      run: |
        mkdir -p ~/go/bin
        curl -sfL "https://github.com/golangci/golangci-lint/releases/download/v${GOLANGCI_LINT_VERSION:?'golangci-lint version is unset'}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.tar.gz" |\
         tar -C ~/go/bin -zx --strip-components=1 "golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64/golangci-lint"

    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup dependency cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Ensure dependencies are downloaded
      run: go mod download

    - name: Run Linter
      env:
        GOLANGCI_LINT_CACHE: ${{ env.RUNNER_TEMP }}
      run: ~/go/bin/golangci-lint run
